name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  easy_localization: ^3.0.7
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_background_service: any
  flutter_background_service_android: "6.0.1"
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^17.2.3
  flutter_slidable: ^3.1.1
  fluttertoast: ^8.2.8
  go_router: ^14.3.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
