// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa1EFr0LGr9BBwdBv75Kc5vzFoRWLkLm0',
    appId: '1:673724474122:web:174de606f97b1d2c8110f3',
    messagingSenderId: '673724474122',
    projectId: 'my-tod0-app',
    authDomain: 'my-tod0-app.firebaseapp.com',
    storageBucket: 'my-tod0-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwWjKT81MgL00tXghtMiHUC7gZNSdJyrQ',
    appId: '1:673724474122:android:bf7c41f78189f6148110f3',
    messagingSenderId: '673724474122',
    projectId: 'my-tod0-app',
    storageBucket: 'my-tod0-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXYCkWxTTBzq3clZ_-mzBV6s1Va24XBs8',
    appId: '1:673724474122:ios:0d02e80f30aee48b8110f3',
    messagingSenderId: '673724474122',
    projectId: 'my-tod0-app',
    storageBucket: 'my-tod0-app.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );
}
